theia-full-docker/Dockerfile, theia-full-docker/latest.package.json, theia-full-docker/next.package.json
This contains theia extensions and corresponding LSPs for:
GO, Java, C/C++, Python, Typescript and YANG.
This Dockerfile is based on Ubuntu 16.04
Signed-off-by: Antoine Tremblay <antoine.tremblay@ericsson.com>
=> Add theia-full-docker

theia-openshift-docker/Dockerfile, theia-openshift-docker/entrypoint
Openshift requires that user not have root user permissions. Openshift defaults to a random user id number that does not have root permissions https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines . This means that passwd file needs to be updated to include random user in startup script to ensure applications run correctly. Permissions of certain folders need be changed to be readable and executed by this random user that belongs to the group "root" by default.
Theia team would need to add an Docker image to the automated builds for docker hub which builds after base image 'theiaide/theia' is built. Name needs to pick for this image but could be 'theiaide/theia-openshift'.
Related issue …
=> Openshift Docker Image

theia-docker/latest.package.json, theia-docker/next.package.json
This PR adds JSON and basic languages highlighting support to theia-docker images. I have not:
- added JSON support to latest, since we publish it only against next;
- changed other images, because I don't want to test them, they can be tackled by other PRs.
=> upgrade theia-docker images

theia-full-docker/latest.package.json
This extension is causing issues for "latest", breaking the coloring. We
can add it back after next release.
Fixes #84
=> [full] Remove @theia/ruby from "latest"

theia-full-docker/Dockerfile, theia-go-docker/Dockerfile
The docker build fails due to outdated golint links. 
Reference: [ead987a](https://github.com/golang/lint/commit/ead987a65e5c7e053cf9633f9eac1f734f6b4fe3)
=> update golint link

theia-docker/Dockerfile
This is in relation to [PR #80](https://github.com/theia-ide/theia-apps/pull/80) as well as additional fixes. Description are on the commits.
Image size is trimmed down to about `307MB` from `414MB`
Signed-off-by: Uni Sayo <unibtc@gmail.com>
=> [theia-docker] trim down docker image size

.travis.yml, tests/.gitignore, tests/LICENSE.3rd-party, tests/bottom-panel/bottom-panel.ts, tests/left-panel/left-panel.ts, tests/left-panel/left-panel.ui-spec.ts, tests/main-page/main-page.ts, tests/main-page/main-page.ui-spec.ts, tests/package.json, tests/right-panel/right-panel.ts, tests/right-panel/right-panel.ui-spec.ts, tests/theia-docker/theia-docker.spec.ts, tests/top-panel/top-panel.ts, tests/top-panel/top-panel.ui-spec.ts, tests/tsconfig.json, tests/wdio.base.conf.js, tests/wdio.conf.js, tests/wdio.theia-docker.conf.js, theia-full-docker/Dockerfile
This commit adds a minimal test suite that validates that the images,
that we build and publish, include a minimally working Theia application.
Until now we relied on the success of an image's build during CI, to
publish it on dockerhub. That's not good, because Theia applications
can sometimes build but not behave correctly or even start.
The UI test suite and related configurations were borrowed from the
main theia repo and slightly adapted. ATM we use only the most basic
test suite, "main-page", that should be applicable to all Theia
applications we run CI on.
This will be enhanced in the future to to add image-specific test
files. For example, see wdio.theia-docker.conf.js, that adds an
extra test file to be run, for the theia-docker image. ATM this second
suite is bogus and just for …
=> Ci add tests

theia-full-docker/Dockerfile
Using ENTRYPOINT would allow node option such as `--inspect` to be passed along for debugging.
Signed-off-by: Uni Sayo <unibtc@gmail.com>
=> [theia-full] Use ENTRYPOINT instead of CMD

theia-full-docker/Dockerfile
It is some kind of IPV6-related issue to ipv4 instead.
refs:
- https://github.com/theia-ide/theia-apps/pull/136#discussion_r261685806
- https://github.com/jacobalberty/unifi-docker/issues/64#issuecomment-454961479
thanks @marcdumais-work
=> docker full: fixed gpg typo (ubuntu 18.04)

theia-full-docker/latest.package.json
ATM it's causing some issues with opening files. We can add
it again once it's adapted to use the version of sprotty that's
hosted at the Eclipse Foundation.
fixes theia-ide/theia#4515 , #142
=> [full:latest] remove theia-yang-extension

theia-go-docker/Dockerfile, theia-go-docker/README.md, theia-go-docker/next.package.json
In order to start one should use:
```
docker run --security-opt seccomp=unconfined -it -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia-go:next
```
It allows ptrace for debugging. When you try it is important to install the project within docker container if you host OS is different.
Debugging https://github.com/demo-apps/go-gin-app:
Closes #141, fix #118
=> [theia-go] migrate next to vscode extension

theia-swift-docker/Dockerfile, theia-swift-docker/latest.package.json, theia-swift-docker/next.package.json
Updated to multistage docker image for building lsp and vscode extension
TODO: remove vscode extension builder in dockerfile after official release,
=> [swift] add theia swift support

theia-electron/package.json
Added missing `@theia/electron` dependency necessary to build the 
`theia-electron` bundled application.
=> [electron] add missing @theia/electron dependency

.travis.yml
Theia switched to supporting node 10 recently, instead of node 8.
That change will be reflected, in published "latest" Theia packages,
once we release 0.6.0; we should then merge this so that the "latest"
images in this repo can be built.
Fixes #171
=> [Travis] Use node 10 for latest images

theia-electron/README.md, theia-electron/package.json
Fixes #173
Fixed the bundled Electron applications which
did not properly start language servers resulting
in missing language support, and features.
- Upgraded `node` version to 10 lts.
- Upgraded `electron-builder` to compatible version with node update.
- Added missing `@theia/textmate-grammars` dependency.
=> Fix electron language support

theia-docker/latest.package.json, theia-docker/next.package.json, theia-electron/package.json, theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-go-docker/latest.package.json, theia-go-docker/next.package.json, theia-java-docker/latest.package.json, theia-java-docker/next.package.json, theia-python-docker/latest.package.json, theia-python-docker/next.package.json, theia-swift-docker/latest.package.json, theia-swift-docker/next.package.json, yangster-docker/latest.package.json, yangster-docker/next.package.json
This reverts commit be26586425b5ec6904ab81be43a0b8836d206e05.
We have a fix, merged in Theia's master branch, that makes
this work-around obsolete. So I am reverting.
=> Revert "[all] add resolution for vscode-uri@1.0.6"

theia-electron/electron-builder.yml
This will make sure that the packaged application use the patched
electron binaries pulled by `@theia/electron`.
Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>
=> [theia-electron] Use locally installed Electron

theia-java-docker/Dockerfile
=> [java] add javac directory in PATH

.travis.yml, CONTRIBUTING.md, README.md, theia-go-docker/README.md, theia-python-docker/README.md
fix https://github.com/theia-ide/theia-apps/issues/195
Signed-off-by: tom-shan <swt0008411@163.com>
=> add --init to docker run

.travis.yml, tests/package.json, theia-cpp-docker/Dockerfile, theia-cpp-docker/README.md, theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-cpp-docker/settings.json
The image includes the nightly build for clangd and command-line
clang-tidy. Also includes a preference to enable the clang-tidy
integration, where it runs co-located with clangd and can "comment"
about linter issues in open files.
Fixes #194
=> [cpp] Added cpp Docker application

.github/stale.yml
Added the probot `stale.yml` configuration file used by the GitHub probot stale integration which
is used to automatically mark issues and pull requests as stale due to inactivity after a certain timeframe and eventually close them if no further actions are performed.
=> Add probot 'stale.yml' config file

theia-docker/latest.package.json, theia-docker/next.package.json
Fixes #106
Added the `@theia/debug` and `@theia/debug-nodejs` dependencies
to the theia-docker image (both `latest` and `next`).
=> Add 'debug' and 'debug-nodejs' to docker image

tests/package.json
I noticed that I was not able to successfully run yarn in the tests
directory, using my new Ubuntu 18.04 install. I updated the test
dependencies to be in-line with the main Theia repo, and now this
builds again.
=> [tests] update dependencies

theia-rpm-build-docker/Dockerfile, theia-rpm-build-docker/README.md, theia-rpm-build-docker/package.json, theia-rpm-build-docker/run_theia.sh
A proof of concept demonstrating how to build a RPM of the cloud IDE.
=> RPM build example

.github/stale.yml
- updated the probot stale bot to exempt the labels `no-stale` and `help wanted`
- updated the `limitPerRun` to only run 5 actions per hour
=> [stale] update 'stale.yml' configuration

theia-go-docker/latest.package.json
One PR added the usage of the VS Code extension to the
latest image while another stepped the version of the
same extension used for next. This third PR steps the
version of the extension used for latest so it matches
the updated next.
=> [go:latest] Align VS Code extension version with next

theia-rust-docker/Dockerfile, theia-rust-docker/README.md, theia-rust-docker/bashrc, theia-rust-docker/ex_bash, theia-rust-docker/makefile, theia-rust-docker/next.package.json, theia-rust-docker/sudoers
There is a problem with the Rust app. Currently the files in the cargo folder are owned by "root". Thus the user is not able to install crates. Even more the cache folder is also not writeable. This causes errors when the RLS wants to cache.
The solution was to add a "rust" group and make all the files in the rust folder (cargo and rustup) part of this group and group writable. When the user creates the container the specific user is created inside the container and added to the rust group. The users umask is set to 0002 so that any changes made to the cargo or cache folders are also group writeable. (Drawback) Note that this will also make all other files created by the user (eg. source code) group writeable.
=> Correct permissions so that crates can be installed as a non-root user

.travis.yml, build_container.sh, check_changed.sh
A proposed solution to issue #214. On each commit only those images will be built/tested that were changed.
I used TRAVIS_EVENT_TYPE to determine if the build was started through a commit or via the dashboard (more options -> trigger build)
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
If a commit is done only the specific image is built/tested.
If "trigger build" is clicked via the travis dashboard, all images are built/tested
=> Travis should only build/test images that have changes

check_changed.sh
When the nightly cron job runs, this needs to trigger a build for all images.
=> Trigger all builds on api or cron job

.travis.yml, tests/wdio.base.conf.js
Fixes #250
- Fix webdriverio by including `addons` with `chrome:stable`.
=> Fix webdriverio tests

.travis.yml
Fixed the failing deployment stage of the Docker images introduced by the following changes https://github.com/theia-ide/theia-apps/pull/236. We used to publish based on `$IMAGE`, yet after refactoring the content to `build_container.sh`, `$IMAGE` is `undefined` and results in a Docker "invalid reference format" error.
Error:
https://travis-ci.org/theia-ide/theia-apps/jobs/594094812#L1071-L1073
=> Fix Travis Deployment

theia-cpp-docker/README.md, theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-cpp-electron/README.md, theia-cpp-electron/package.json
Fixes #227
- added `@theia/cpp-debug` dependency to the `theia-cpp-docker:latest` image.
- added `@theia/cpp-debug` dependency to the `theia-cpp-docker:next` image.
- added `@theia/cpp-debug` dependency to the `theia-cpp-electron` application.
- updated documentation present in the `theia-cpp-docker` readme.
- updated documentation present in the `theia-cpp-electron` readme.
=> Add 'cpp-debug' dependency

theia-electron/electron-builder.yml
Fixes #267
- adds support for _macOS_ dark theme for the electron window.
- adds support for _macOS_ dark theme for the electron native menus.
| Light Window | Dark Window |
|:---:|:---:|
| <img width="1205" alt="Screen Shot 2019-11-13 at 8 42 11 AM" src="https://user-images.githubusercontent.com/40359487/68769403-3a815380-05f2-11ea-9911-707cb11453f6.png"> |<img width="1205" alt="Screen Shot 2019-11-13 at 8 42 34 AM" src="https://user-images.githubusercontent.com/40359487/68769423-440abb80-05f2-11ea-8ebd-37595e16bef9.png"> |
| Light Menu | Dark Menu |
|:---:|:---:|
| <img width="456" alt="Screen Shot 2019-11-13 at 8 45 03 AM" src="https://user-images.githubusercontent.com/40359487/68769492-669cd480-05f2-11ea-8685-4f5c2d90948f.png">| <img width="456" alt="Screen Shot 2019-11-13 at 8 44 26 …
=> Add support for dark theme on macOS

.travis.yml, build_container.sh, tests/package.json, tests/wdio.theia-https.conf.js, theia-https-docker/Dockerfile, theia-https-docker/README.md, theia-https-docker/ssl_theia.sh, theia-https-docker/theiahere
This image adds **token authentication** and **https** to theia, to make your coding sessions more secure. The security is added by means of [gen-http-proxy](https://www.npmjs.com/package/gen-http-proxy), which is a generic http proxy that enables https and token authentication.
Run on https://localhost:10443 with the current directory as a workspace (creating a random token):
```console
docker run --init -it -p 10443:10443 -v "$(pwd):/home/project:cached" theiaide/theia-https:latest
generating key file for https
generating cert file for https
root INFO Theia app listening on http://localhost:3000.
redirecting to localhost:3000
access url: https://0.0.0.0:10443?token=0f34fd329f266caca309bd47f8f8cc6f
token: 0f34fd329f266caca309bd47f8f8cc6f
use cookies: true
expiration: 60
```
It should be …
=> https and token authentication for theia-ide

.editorconfig, .theia/settings.json, .vscode/extensions.json, .vscode/settings.json, theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-cpp-electron/package.json, theia-dart-docker/latest.package.json, theia-dart-docker/next.package.json, theia-deb-build-docker/package.json, theia-docker/latest.package.json, theia-docker/next.package.json, theia-electron/package.json, theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-go-docker/latest.package.json, theia-go-docker/next.package.json, theia-java-docker/latest.package.json, theia-java-docker/next.package.json, theia-python-docker/latest.package.json, theia-python-docker/next.package.json, theia-rpm-build-docker/package.json, theia-ruby-docker/latest.package.json, theia-rust-docker/next.package.json, theia-swift-docker/latest.package.json, theia-swift-docker/next.package.json, yangster-docker/latest.package.json, yangster-docker/next.package.json
Fixes #271
Fixes #233
- fixes issue where JSON language server did not provide content assist
- fixes issue where JSON language server did not provide hover information
- fixes issue where JSON language server did not generate markers
- similar fix provided by the main repository eclipse-theia/theia#6607
🏅 Bonus:
- added `.editorconfig` file to have consistent formatting across the repo
- added `settings.json` for development through Theia
- added `setting.json` and `extensions.json` for development through VS Code
1. build and run an image
2. open the `preferences` widget
3. determine if the file has content assist, validation, hover info
- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#review …
=> Fix JSON language server features

theia-full-docker/Dockerfile
There was a typo, making the SHELL var corrupted.
=> Fix SHELL environment variable

theia-electron/.gitignore, theia-electron/package.json
For some reason the Electron example now fails during packaging,
complaining about a couple of unresolved dependencies. So I added
them.
Fixes #292
=> [electron] Add a couple of dev-dependencies

.travis.yml, theia-full-docker/next.package.json
Due to limited resources the yangster-related extensions may not keep-up
with the latest Theia platform at all times. To minimize CI issues here,
this commit removes the theia-yangster image (both latest and next) from
CI, and also removes theia-yangs-extension from theia-full:next.
Fixes #294
=> [yangster][full] fix CI

theia-cpp-docker/Dockerfile, theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-java-docker/latest.package.json, theia-java-docker/next.package.json
The following pull-request adds some changes both to the `theia-java` and `theia-cpp` images:
- moves `@theia/cli` to `devDependencies`.
- removes the `typescript` dependency since it is included with the builtin.
- removes the `vscode-builtin-markdown-language-features` extension in favor of `@theia/preview`.
- calls the `download:plugins` script before the actual build.
Verify that the CI successfully passes (`theia-java` + `theia-cpp`)
=> java/cpp: cleaup images

theia-java-docker/Dockerfile, theia-python-docker/Dockerfile, theia-ruby-docker/Dockerfile
Fixes #317
This commit increases the `node` memory size when building the application in the `theia-java`, `theia-python` and `theia-ruby` images. The same [change](https://github.com/theia-ide/theia-apps/search?q=--max_old_space_size&unscoped_q=--max_old_space_size) was done for other images already.
- the `theia-java` full and latest images should successfully build (verify CI)
=> increase node memory size when building

theia-electron/package.json
Closes #319
I have verified it locally, it builds and runs.
Upstream ref: https://github.com/electron-userland/electron-builder/issues/3990#issuecomment-539916169
Signed-off-by: Akos Kitta <kittaakos@typefox.io>
=> Bumped up the 'electron-builder' version

theia-cpp-docker/Dockerfile, theia-full-docker/Dockerfile
Bump CMake from 3.10.2 to 3.17.0 (the latest stable) using the kitware installer.
=> Update CMake for theia-cpp images

theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-cpp-electron/package.json, theia-dart-docker/latest.package.json, theia-dart-docker/next.package.json, theia-deb-build-docker/package.json, theia-docker/latest.package.json, theia-docker/next.package.json, theia-electron/package.json, theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-go-docker/latest.package.json, theia-go-docker/next.package.json, theia-java-docker/latest.package.json, theia-java-docker/next.package.json, theia-python-docker/latest.package.json, theia-python-docker/next.package.json, theia-rpm-build-docker/package.json, theia-ruby-docker/latest.package.json, theia-ruby-docker/next.package.json, theia-rust-docker/next.package.json, theia-swift-docker/latest.package.json, theia-swift-docker/next.package.json, yangster-docker/latest.package.json, yangster-docker/next.package.json
1.2.3 seems to cause incompatibities.
Fixes #333
Signed-off-by: Jérome Perrin <jerome@nexedi.com>
=> Pin vscode-json-languageserver to 1.2.2

.travis.yml
This commit removes `rust` from CI since it is somewhat fragile, and fails with the same error from the past: https://github.com/theia-ide/theia-apps/issues/253
---
@dwjbosman are you fine with the following approach? It looks like rust fails to build due to the same issue regarding the channel date. We can always add back CI for rust if/when the image becomes more stable.
=> rust: remove rust from CI

.travis.yml, theia-rust-docker/Dockerfile, theia-rust-docker/next.package.json
We've been having issues for a while with the Rust image in CI. We're temporarily removed it so that CI can pass, but would like to being it back when the issues are fixed. 
For a while, it looked like the Rust tools were causing the CI issue. A recent update seems to have remove this problem: https://github.com/theia-ide/theia-apps/pull/330#issuecomment-611981825 . So I thought I would give it a try and see what other issues there might be. 
In addition to adding the image back into CI, this PR:
- Removes deprecated @theia/editorconfig (prevented app from starting, though it compiled)
- Adds environment variable so that plugins (VS Code extensions) defined  in package.json are detected/used
=> [CI] [Rust] Add-back the Rust image to CI

theia-rust-docker/Dockerfile
Like we've been doing for most images. This avoids occasional
"JavaScript heap out of memory" build issues.
Fixes #346
=> [rust] use "--max_old_space_size=4096" option

theia-cpp-docker/README.md, theia-cpp-docker/next.package.json
We can only do this change for `next` at the moment because some recently merged features are required to run `vscode-clangd` in Theia applications. We can do `latest` after this month's release.
- remove `@theia/cpp`
- add `vscode-clangd` 
- README update
=> [next][cpp] switch to vscode-clangd language client

theia-cpp-docker/latest.package.json, theia-dart-docker/latest.package.json, theia-deb-build-docker/package.json, theia-docker/latest.package.json, theia-full-docker/latest.package.json, theia-go-docker/latest.package.json, theia-java-docker/latest.package.json, theia-php-docker/latest.package.json, theia-python-docker/latest.package.json, theia-rpm-build-docker/package.json, theia-ruby-docker/latest.package.json, theia-swift-docker/latest.package.json, yangster-docker/latest.package.json
Fixes #354 
The following pull-request fixes the breaking changes caused by **momentjs**  which ultimately results in the main-menu not being rendered successfully. The fix includes adding `resolutions` to the `latest` images only since `next` are fixed by the upstream change: https://github.com/eclipse-theia/theia/pull/7727
1. run any of the docker images (ex: theia-java) and confirm that the main-menu exists.
=> bug: fix momentjs dependency

theia-full-docker/Dockerfile
Fix for the build failing at the go linter "go get" on line 110.  Inspiration for the fix came from this thread [https://github.com/golangci/golangci-lint/issues/1037](https://github.com/golangci/golangci-lint/issues/1037) in the golangci repo itself where others were having a similar issue.
- changed go get in line 110 to use go modules.
=> Fix for build failing at go linter

theia-go-docker/Dockerfile
This commit fixes the `golangci-lint` dependency which caused the **golang** images to fail.
=> golang: fix build failure

theia-cpp-electron/README.md, theia-cpp-electron/package.json
Replacing @theia-cpp, that will soon be deprecated.
As well updated the scripts in `package.json` so that the
vscode extensions are downloaded during build and used when
starting the example application.
=> [cpp-electron] update app to use vscode-clangd for C/C++

theia-cpp-docker/Dockerfile, theia-cpp-docker/README.md
This PR is to add ppc64le support. We are downgrading the versions of the tools clang-tools-11, clangd-11 and clang-tidy-11 to clang-tools-9, clangd-9 and clang-tidy-9. As per https://apt.llvm.org that provides list of clang packages available for different platforms, clang-tools-9, clangd-9 and clang-tidy-9 are the latest versions that support POWER platform.
Signed-off-by: sailaja Chavali sachav83@in.ibm.com
=> Adding support for ppc64le platform

theia-full-docker/Dockerfile, theia-full-docker/latest.package.json, theia-full-docker/next.package.json
Please review. One drawback is that the dart SDK is installed to Dockerimage for stable and next image.
=> Add dart sdk to full image and install dart and flutter extensions to next image

.travis.yml, build_container.sh, commit_screenshots.sh, theia-electron/package.json
Signed-off-by: thegecko <rob.moran@arm.com>
This PR introduces electron builds and publishing from TravisCI for the master branch.
I've already created a test publish of the installers here: https://github.com/theia-ide/theia-apps/releases/tag/v0.1.0
__Note:__ These installer binaries are untested and currently unsigned. I will create a separate PR later to introduce signing for macOS and Windows.
- Added Travis CI jobs to build installers for macOS/Windows/Linux in addition to existing docker jobs which only run on master
- Updated `theia-electron` project to use `latest` theia by default to be more stable for users
- Updated git repository URLs in `theia-electron` project to point at this repo (as it's used by electron-builder for publishing)
- Automatic publishing of installers to …
=> Added Travis CI jobs to publish installers

.travis.yml
Signed-off-by: thegecko <rob.moran@arm.com>
This PR fixes an oversight in the recent travis changes to stop docker commands during a build job for the installers.
=> [ci] Skip before_deploy for installer builds

README.md, theia-full-docker/Dockerfile
Add swift language tools to full image. If you want to use the swift REPL, these options have to be provided to docker: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined
=> [full] Add Swift SDK to full image

.travis.yml
Signed-off-by: Rob Moran <rob.moran@arm.com>
This PR fixes the failing build in master by skipping the `deploy` step for installers based on environment variables rather than skipping the stage.
It also introduces a timeout for when macOS installer generation takes longer than 10 minutes and is timed out.
Apologies for the oversight, Travis-CI is a [bit weird](https://travis-ci.community/t/unable-to-skip-deploy/9042).
=> Ignore deploy for installers and add timeout

theia-cpp-docker/next.package.json, theia-dart-docker/next.package.json, theia-docker/next.package.json, theia-full-docker/next.package.json, theia-go-docker/next.package.json, theia-java-docker/next.package.json, theia-php-docker/next.package.json, theia-python-docker/next.package.json, theia-ruby-docker/next.package.json, theia-rust-docker/next.package.json, theia-swift-docker/next.package.json, yangster-docker/next.package.json
Fixes: #379
The following pull-request replaces the deprecated `@theia/json` dependency from the `next` images, with the vscode builtin counterpart `vscode-builtin-language-features:
- removes the dependency from the next images
- adds the builtin dependency for json
- removes the unused resolutions
- verify the CI passes
- verify that the json language features work correctly (ex: editing the `settings.json`)
=> next: replace deprecated json dependency

theia-cpp-docker/latest.package.json, theia-cpp-electron/package.json, theia-dart-docker/latest.package.json, theia-deb-build-docker/package.json, theia-docker/latest.package.json, theia-electron/package.json, theia-full-docker/latest.package.json, theia-go-docker/latest.package.json, theia-java-docker/latest.package.json, theia-php-docker/latest.package.json, theia-python-docker/latest.package.json, theia-rpm-build-docker/package.json, theia-ruby-docker/latest.package.json, theia-swift-docker/latest.package.json, yangster-docker/latest.package.json
Fixes: https://github.com/theia-ide/theia-apps/issues/381
The following pull-request updates all **latest** docker images and electron builds to replace the now deprecated `@theia/json` extension with the `vscode-builtin-json-language-features` counterpart.
- remove references of `@theia/json` (next was completed last month https://github.com/theia-ide/theia-apps/pull/380).
- include `vscode-builtin-json-language-features` plugin.
- removed unused `resolutions`.
The CI should be successful.
=> json: replace json extension with vscode ext

theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-cpp-electron/package.json, theia-electron/package.json, theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-php-docker/latest.package.json, theia-php-docker/next.package.json, theia-rust-docker/next.package.json, yangster-docker/latest.package.json, yangster-docker/next.package.json
Fixes: #387 
The following pull-request removes the deprecated `@theia/languages` extension from both images and apps in favor of using vscode extensions to provide language-support.
Verify that CI passes successfully.
=> languages: drop '@theia/languages'

theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-cpp-electron/package.json, theia-full-docker/Dockerfile, theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-rust-docker/next.package.json
The following pull-request removes deprecated `@theia` language extensions
and replaces them with vscode counterparts when appropriate.
- removes `@theia/php`.
- removes `@theia/rust`.
- removes `@theia/plantuml` and includes the vscode extension.
Verify that CI passes successfully.
=> ext: remove deprecated language extensions

theia-cpp-docker/Dockerfile, theia-full-docker/Dockerfile, theia-go-docker/Dockerfile
Update CMake to latest version 3.18.1, dart sdk to latest version 2.9.0 and go lang to latest version 1.15.
Signed-off-by: Christoph Bayer <chrbayer@criby.de>
=> Update CMake, dart sdk and go lang.

theia-docker/Dockerfile, theia-php-docker/Dockerfile
**Problem:**
- Current Dockerfile does not contain the libs that are required in [prerequisites ](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites)section for "[Build your own IDE](https://theia-ide.org/docs/composing_applications/)" section on theia-ide.org.  
- This works fine on localhost, but it gives errors while loading the URL from a remote machine and accessing the VS Code extensions. 
**Steps to Reproduce**
- Build theia docker image with the current docker file and in package.json add the VS Code extensions that are the part of IBM Wazi [workspace](https://www.ibm.com/support/knowledgecenter/SSCH39_1.0.0/wazi/installation_packages.html#installation_packages__code_client). 
- Try to access theia from remote machine and use VS Code extensions. …
=> Added the libraries that are the prerequisites for theia-ide.org

theia-full-docker/Dockerfile
Fixes the recent build error on `theia-full` regarding the python installation:
```
ERROR: Could not find a version that satisfies the requirement ujson>=3.0.0 (from python-language-server) (from versions: 1.4, 1.6, 1.8, 1.9, 1.15, 1.18, 1.19, 1.21, 1.22, 1.23, 1.30, 1.33, 1.34, 1.35, 2.0.0, 2.0.1, 2.0.2, 2.0.3)
ERROR: No matching distribution found for ujson>=3.0.0 (from python-language-server)
The command '/bin/sh -c apt-get update     && apt-get install -y software-properties-common     && add-apt-repository -y ppa:deadsnakes/ppa     && apt-get install -y python-dev python-pip     && apt-get install -y python3.8 python3-dev python3-pip     && apt-get remove -y software-properties-common     && python -m pip install --upgrade pip --user     && python3.8 -m pip install …
```
=> full: fix python build error

theia-python-docker/Dockerfile
The following commit updates the `theia-python-docker` image to a multi-stage build approach, where we build the application in the first stage and copy it over to the second (first layer is not preserved). 
=> python: update python image

theia-full-docker/Dockerfile
+ Fixes #394 
+ Adds environment variables to disable .NET telemetry, .NET welcome message
**Note**: The following message from telemetry will still be in the log. It is a default setting from Microsoft. [See this](https://github.com/dotnet/sdk/issues/8112#issuecomment-294163843)
>Telemetry
>---------
>The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
=> [full] Disable .NET SDK Telemetry and .NET welcome message

theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-cpp-electron/package.json, theia-dart-docker/latest.package.json, theia-dart-docker/next.package.json, theia-docker/latest.package.json, theia-docker/next.package.json, theia-electron/package.json, theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-go-docker/latest.package.json, theia-go-docker/next.package.json, theia-php-docker/latest.package.json, theia-php-docker/next.package.json, theia-python-docker/latest.package.json, theia-python-docker/next.package.json, theia-rust-docker/next.package.json, theia-swift-docker/latest.package.json, theia-swift-docker/next.package.json
+ Fixes #384 
+ Adds `vscode-builtin-html-language-features` builtin vscode extension all images and apps
=> html: include 'vscode-builtin-html-language-features' vscode extension

theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-go-docker/latest.package.json, theia-go-docker/next.package.json
+ Fixes #378
+ VS Code Go extension has moved to the go community ([blog post](https://blog.golang.org/vscode-go)). It's currently available on [open-vsx](https://open-vsx.org/extension/golang/Go). This PR updates the source link of `vscode-go` to version  `0.16.2`, which is the latest version at the moment.
=> [full, go] Update `vscode-go` publisher

.travis.yml
This reverts commit 31872398ae52dac2c08318f6d30b157baad7dcf9.
After all images we publish have been updated to use two stages,
we are able to re-enable publishing to dockerhub.
The reason for the update is that we realized that build arguments
are saved in the image's history, even if not present in the final
image as such. This means the GH token, used during the build,
was present for anyone to see, in the history of images we were
publishing. The old tokens have been revoked, and from now-on
the Theia app is built in a first stage that's discarded from the
final, published image.
=> Revert "[temporary] Disable publish to dockerhub"

theia-swift-docker/Dockerfile
The following pull-request fixes the `theia-swift-docker` build caused by the missing `postinstall` script for the `sourcekit-lsp` extension: https://github.com/apple/sourcekit-lsp/blob/6511ca732e5957f6ef4f48760e11e7c1643632dc/Editors/vscode/package.json#L23-L28
```json
"scripts": {
"vscode:prepublish": "npm run compile",
"compile": "tsc -p ./",
"watch": "tsc -watch -p ./",
"createDevPackage": "npm install && ./node_modules/.bin/vsce package -o ./out/sourcekit-lsp-vscode-dev.vsix"
},
``` 
**How to test**
- the CI for the `theia-swift-docker` image should now successfully pass.
=> swift: fix postinstall build error

theia-swift-docker/Dockerfile
previously were using custom images for sourcekit-lsp, now moving to the official swift docker image.
=> [swift] move to the official swift docker image

.github/workflows/ci-cd.yml, build_container.sh, check_changed.sh, theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-dart-docker/latest.package.json, theia-dart-docker/next.package.json, theia-docker/latest.package.json, theia-docker/next.package.json, theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-go-docker/latest.package.json, theia-go-docker/next.package.json, theia-php-docker/latest.package.json, theia-php-docker/next.package.json, theia-python-docker/latest.package.json, theia-python-docker/next.package.json, theia-rust-docker/next.package.json, theia-swift-docker/latest.package.json, theia-swift-docker/next.package.json
+  The workflow is [failing](https://github.com/theia-ide/theia-apps/actions/runs/398586435) for some images. This PR attempts to address the issue and also fix potential problems by:
- Change `ubuntu-latest` to `ubuntu-18.04` as the latest version soon will be `20.04`
- Fix wrongly passing `GITHUB_TOKEN` in `build_container`
- Fix `node-gyp` error by attempting to call `node-gyp install` first (https://github.com/nodejs/node-gyp/issues/1780#issuecomment-503976718)
+ The CI should pass
**Note**: The CI may fail for `rust` images since it's an existing issue with `racer`. This PR doesn't cover the fix for it.
=> Patch: Fix build fails in some images

theia-deb-build-docker/Dockerfile, theia-deb-build-docker/package.json
Minimal fix for this image. The example app would need to be updated
to support vscode extensions to be useful.
I was thinking that this may be the only example we have of packaging a 
browser Theia app, along with the `rpm` example. So we may consider 
updating the app, building a `.deb` and using it to install the app in DEBIAN
-based containers. (not in this PR though)
=> [deb] fix image

.github/workflows/ci-cd.yml
Closes #454 
+ Use [login-action](https://github.com/docker/login-action) instead of manually log in to DockerHub (https://github.com/theia-ide/theia-apps/issues/454#issuecomment-764937973).
+ Can only test login when the PR is merged to master. It should work if `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` present correctly in the repo secrets (same as [this](https://github.com/DukeNgn/minimal-docker-image/runs/1745457774))
=> CI: Use login-action to log in DockerHub

.github/workflows/ci-cd.yml
+ Sometimes, the [CI fails and the job stales](https://github.com/theia-ide/theia-apps/actions/runs/516616673) for a long time (6 hours by default). 
+ This PR sets maximum timeout minutes to 120 instead of the default 360. 
+ [GitHub uses 360 as default for `timeout-minutes`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes)
=> CI: Set timeout-minutes per job to 120 minutes

.github/workflows/ci-cd.yml
+ This commit fixes a typo in the CI-CD workflow file. 
+ [`timeout-minutes`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) is the correct syntax .
=> CI: Fix typo

theia-cpp-docker/Dockerfile, theia-cpp-docker/latest.package.json, theia-cpp-docker/next.package.json, theia-cpp-electron/package.json, theia-full-docker/Dockerfile, theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-rust-docker/next.package.json
Closes #462 
Update `vscode-clangd` and `plantuml` to the latest version from open-vsx.
+ `vscode-clangd` to `0.1.7`
+ `plantuml` to `2.14.0`
=> Update download links for plantuml and clangd

.github/workflows/ci-cd.yml
Fix #465 
+ Specify the image tag (`next` or `latest`) when deploying to DockerHub. This prevents `docker push` to use the default `latest` tag for `next` images
+ The syntax is now following the format `docker push <hub-user>/<repo-name>:<tag>` from [Docker Documentation](https://docs.docker.com/docker-hub/repos/#pushing-a-docker-container-image-to-docker-hub)
=> CI: Define tag when deploy docker images

.github/workflows/ci-cd.yml, build_container.sh
This PR adds the ability to tag and deploy a docker image with its solid version.
+ Update `build_container.sh` to only tag images with its solid version when the `NPM_TAG` is `latest`.
+ Add a step in the CI to determine the version and publish with a solid tag.
+ [push with `--all-tags` option of an image](https://docs.docker.com/engine/reference/commandline/push/#push-all-tags-of-an-image)
+ [`tag` command from docker CLI](https://docs.docker.com/engine/reference/commandline/tag/)
+ The CI should pass 
+ Verify in the `build` step of `latest` images, the script successfully tagged the image with a solid version. For example, `theiaide/theia` image should have 2 tags: `1.12.1` and `latest`:
+ A minimal repo was set up to test similar use-case:
- [Successful …
=> CI: Add steps to deploy solid version of the images

theia-cpp-docker/Dockerfile, theia-dart-docker/Dockerfile, theia-docker/Dockerfile, theia-full-docker/Dockerfile, theia-go-docker/Dockerfile, theia-php-docker/Dockerfile, theia-python-docker/Dockerfile, theia-rust-docker/Dockerfile, theia-swift-docker/Dockerfile
It's required starting with Theia 1.15.0. It may still be missing
in some images
Also updared the GPG key servers that were interfering with the
build of a couple of imafges lately.
=> [misc images] add new Theia runtime dependency: libsecret

theia-cpp-docker/Dockerfile, theia-dart-docker/Dockerfile, theia-docker/Dockerfile, theia-full-docker/Dockerfile, theia-go-docker/Dockerfile, theia-php-docker/Dockerfile, theia-python-docker/Dockerfile, theia-rust-docker/Dockerfile, theia-swift-docker/Dockerfile
Adding `libsecret-dev` as a build dependency and switching to the non-dev version of this library for runtime.
=> [misc images] Add libsecret as build dependency, in addition to runtime dependency

theia-cpp-docker/Dockerfile, theia-full-docker/Dockerfile
**What it does**
The commit updates `llvm` to `14` which is the latest bleeding edge.
=> cpp: update `llvm` to 14

theia-full-docker/latest.package.json, theia-full-docker/next.package.json, theia-python-docker/latest.package.json, theia-python-docker/next.package.json
Fixes: #485
The current docker image theiaide/theis-python will not debug python code. In building local Theia IDEs, the ms-python versions that work are in the range 2020.7.96456 to 2020.10.332292344.
Versions after 2020.8.105369, however, break the nice (but not strictly necessary) feature of showing the workspace python version in the status bar.
Updating the package.json files that include a download for the ms-python plugin.
Also, switching to use of OpenVSX as the download source.
=> update ms-python version to 2020.8.105369

tests/top-panel/top-panel.ts, tests/top-panel/top-panel.ui-spec.ts, tests/wdio.base.conf.js
**What it does**
The pull-request enables additional tests for docker images which were otherwise not executed.
The `top-panel` tests were simplified and should now cover cases where the top-panel is visible but no menus are present, and should hopefully help identify issues like https://github.com/theia-ide/theia-apps/issues/494.
The following images are expected to fail:
- `theia-cpp-docker` due to https://github.com/theia-ide/theia-apps/issues/494
- `theia-full-docker` due to https://github.com/theia-ide/theia-apps/issues/494
=> ci: enable additional tests

.github/workflows/ci-cd.yml, README.md
This commit removes all images from CI except theia-full,
disables publishing to Docker Hub and adds a note to root
README. These are the first steps of the repo's ramp-down,
as documented in :
https://github.com/theia-ide/theia-apps/issues/496
=> Removed images from CI, Disabled Docker Hub publish, added README note

theia-cpp-docker/Dockerfile
LLVM 14 relies on GCC 10 related packages which are now missing from Ubuntu 18.04
=> Fixed missing gcc 10 dependencies
