- theia-java-docker/Dockerfile
- theia-java-docker/latest.package.json
- theia-java-docker/next.package.json
We'd like to add a second Theia docker image, which contains the Java language server extension.
> [docker] add theia with java extension

- .travis.yml
It should fix the build: https://travis-ci.org/theia-ide/theia-apps/builds/365328452
> Use --password-stdin instead of --password

- README.md
Signed-off-by: Anton Kosiakov <anton.kosyakov@typefox.io>
> fixed links in README

- theia-full-docker/next.package.json
> Fixed version of yang extension

- .travis.yml
- theia-docker/Dockerfile
- theia-full-docker/Dockerfile
- theia-go-docker/Dockerfile
- theia-java-docker/Dockerfile
- theia-sadl-docker/Dockerfile
- yangster-docker/Dockerfile
plus it reverts stages to run in parallel
> declare GitHub token env variable

- .travis.yml
> add theia-full build

- .travis.yml
- CONTRIBUTING.md
- theia-docker/Dockerfile
- theia-full-docker/Dockerfile
- theia-full-docker/next.package.json
- theia-go-docker/Dockerfile
- theia-java-docker/Dockerfile
- theia-python-docker/Dockerfile
- theia-python-docker/README.md
- theia-python-docker/latest.package.json
- theia-python-docker/next.package.json
- theia-ruby-docker/Dockerfile
- theia-ruby-docker/latest.package.json
- theia-ruby-docker/next.package.json
- theia-sadl-docker/Dockerfile
- theia-sadl-docker/README.md
- yangster-docker/Dockerfile
A quick branch fix of #35 due to squashing problems.
Supersedes(Closes #10) and resolves #34 
Note: I can't seem to get squashing by rebase right, Maintainer edit is enabled so you guys can assist me with this
> Theia IDE on user mode

- theia-full-docker/Dockerfile
That prevented the full image from running correctly.
------
This is a follow-up on https://github.com/theia-ide/theia-apps/pull/56#issuecomment-415787240
> [full] fixed permission issue

- theia-electron-builder/Dockerfile
- theia-electron-builder/README.MD
Closes: #77.
Signed-off-by: Akos Kitta <kittaakos@typefox.io>
> GH-77: Added image to building electron applications for Windows on UNIX

- theia-full-docker/Dockerfile
Switched to openjdk from Oracle jdk
Use latest development clangd-9
> [full] update clangd and java JDK

- theia-docker/Dockerfile
- theia-full-docker/Dockerfile
- yangster-docker/Dockerfile
Hopefully will fix the [out-of-memory](https://travis-ci.org/theia-ide/theia-apps/jobs/482650821#L3759) problems we see in CI for the full image
> Fix CI "Allocation failed - JavaScript heap out of memory" issue

- theia-go-docker/Dockerfile
ref: https://blog.golang.org/go1.12
> upgrate golang to 1.12

- theia-full-docker/Dockerfile
> Docker full upgrate to Ubuntu 18.04

- .travis.yml
- tests/package.json
... on dockerhub, when successful
> [theia-swift] add travis CI job and publish

- theia-full-docker/Dockerfile
- theia-java-docker/Dockerfile
> [full,java] Add Maven, Gradle

- .travis.yml
- theia-docker/Dockerfile
- theia-full-docker/Dockerfile
- theia-go-docker/Dockerfile
- theia-java-docker/Dockerfile
- theia-python-docker/Dockerfile
- theia-swift-docker/Dockerfile
- yangster-docker/Dockerfile
I've not had time to test them yet. I will do for theia and go images, but i need help with testing other images.
Right now, i don't expect that next images work at all, so help with testing is appreciated!
fix #161
> upgrade next images to use node 10

- theia-docker/Dockerfile
- theia-go-docker/Dockerfile
- theia-swift-docker/Dockerfile
- yangster-docker/Dockerfile
fix #163
electron is not distributed anymore by default: https://github.com/theia-ide/theia/pull/4873
> get rid of electron deps

- theia-full-docker/latest.package.json
- theia-full-docker/next.package.json
See https://github.com/theia-ide/theia/pull/4876
> get rid of extension manager

- tests/left-panel/left-panel.ts
- tests/left-panel/left-panel.ui-spec.ts
- tests/top-panel/top-panel.ts
- tests/top-panel/top-panel.ui-spec.ts
- theia-docker/latest.package.json
- theia-docker/next.package.json
- theia-electron/package.json
- theia-full-docker/latest.package.json
- theia-full-docker/next.package.json
- theia-go-docker/latest.package.json
- theia-go-docker/next.package.json
- theia-java-docker/latest.package.json
- theia-java-docker/next.package.json
- theia-python-docker/latest.package.json
- theia-python-docker/next.package.json
- theia-swift-docker/latest.package.json
- theia-swift-docker/next.package.json
- yangster-docker/latest.package.json
- yangster-docker/next.package.json
I covered all applications we have in the CI and the electron one as well, that I know is sometimes used. 
Fixes #183
> [all applications] Fix CI

- theia-swift-docker/Dockerfile
moved swift version from 5.0 development snapshot to 5.0.1 release docker image.
> move to swift 5.0.1 stable release

- theia-full-docker/latest.package.json
- theia-full-docker/next.package.json
Add `@theia/debug` and `@theia/debug-nodejs` dependenciesto the `latest` and `next` `package.json`.
> [full] add @theia/debug dependency

- theia-deb-build-docker/Dockerfile
- theia-deb-build-docker/README.md
- theia-deb-build-docker/package.json
- theia-deb-build-docker/run_theia.sh
This is a proof of concept demonstrating how to wrap Theia up into a debian package.
Signed-off-by: Joshua Bradley <jgbradley1@gmail.com>
> Debian build example

- theia-cpp-docker/latest.package.json
- theia-cpp-docker/next.package.json
- theia-docker/latest.package.json
- theia-docker/next.package.json
- theia-full-docker/latest.package.json
- theia-full-docker/next.package.json
- theia-go-docker/latest.package.json
- theia-go-docker/next.package.json
- theia-java-docker/latest.package.json
- theia-java-docker/next.package.json
- theia-python-docker/latest.package.json
- theia-python-docker/next.package.json
- theia-ruby-docker/latest.package.json
- theia-ruby-docker/next.package.json
- theia-swift-docker/latest.package.json
- theia-swift-docker/next.package.json
- yangster-docker/latest.package.json
- yangster-docker/next.package.json
Fixes #82 
Fixes #159 
This PR contains the following fixes:
- added the `@theia/tslint` dependency to images containing `@theia/typescript` images
- set the preference `files.enableTrash` to **false** for all images
> Miscellaneous updates including new dependency and updated preferences 

- .travis.yml
- tests/package.json
- theia-dart-docker/Dockerfile
- theia-dart-docker/latest.package.json
- theia-dart-docker/next.package.json
note: flutter not added. only dart-lang added
> [dart] add theia-dart-docker

- theia-cpp-docker/Dockerfile
- theia-full-docker/Dockerfile
Reverts theia-ide/theia-apps#229
Probably GitHub "Merge commit" was mistakenly used, losing 
original authorship of one of the commits. Will re-merge to fix.
> Revert "Clang10"

- theia-cpp-docker/Dockerfile
- theia-full-docker/Dockerfile
Re-trying to merge the content of PR #229 in a way that preserves the original contained commits.
> Clangd10 take2

- .travis.yml
We thought that depth=1 was good enough, but now CI fails. Let's
try value 2 and see if it's better.
> [travis] try cloning with depth=2

- check_changed.sh
> Build theia-docker in case no specific images were changed

- theia-cpp-docker/latest.package.json
- theia-cpp-docker/next.package.json
- theia-cpp-electron/package.json
- theia-dart-docker/latest.package.json
- theia-dart-docker/next.package.json
- theia-deb-build-docker/package.json
- theia-docker/latest.package.json
- theia-docker/next.package.json
- theia-electron/package.json
- theia-full-docker/latest.package.json
- theia-full-docker/next.package.json
- theia-go-docker/latest.package.json
- theia-go-docker/next.package.json
- theia-java-docker/latest.package.json
- theia-java-docker/next.package.json
- theia-python-docker/latest.package.json
- theia-python-docker/next.package.json
- theia-rpm-build-docker/package.json
- theia-ruby-docker/latest.package.json
- theia-ruby-docker/next.package.json
- theia-rust-docker/next.package.json
- theia-swift-docker/latest.package.json
- theia-swift-docker/next.package.json
- yangster-docker/latest.package.json
- yangster-docker/next.package.json
Signed-off-by:Jacques Bouthillier <jacques.bouthillier@ericsson.com>
**Reference issue**
Fix #260 
**What it does**
It allows to save the text modification after editing.
**How to test**
Open any Theia-app
Open a file in the editor 
Make any modification  
Save it
**Review checklist**
**Reminder for reviewers**
> fix issue #260 - editor can no longer be saved

- theia-full-docker/Dockerfile
So that we can use Theia plugins / VS Code extensions in this image.
Also fixes full image build.
Fixes #263
> [full] Define THEIA_DEFAULT_PLUGINS, fix build

- build_container.sh
> [ci] WIP Fix CI

- theia-rust-docker/Dockerfile
- theia-rust-docker/makefile
Fix for #253 
Channel date has been updated.
> Fix for #253 - Rust Channel update

- theia-full-docker/Dockerfile
- theia-go-docker/Dockerfile
Fixes #329
The following pull-request fixes the theia-full latest and next build caused by an incorrect dependency path for **golint** necessary for golang. The update also includes bumping the version of go in theia-full.
Verify that CI successfully passes for `theia-full` latest and next images.
> full: fix build failure due to golang dependency

- README.md
PowerShell can also understand the dollar-and-bracket expression, so no need to send them to the CMD. See https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10/41489151#41489151 for reference. This pull request is based on #332.
> Add reference to PowerShell

- theia-full-docker/latest.package.json
- theia-full-docker/next.package.json
Added missing PHP plugins for the full image.  Should fix #351
> Added PHP plugins missing from the full image

- theia-full-docker/Dockerfile
Add .NET Core SDK to full images.
> [full] Add .NET Core SDK 3.1

- .travis.yml
Necessary for a little while, until we are done with an ongoing update
> [temporary] Disable publish to dockerhub

- theia-electron/package.json
- theia-full-docker/Dockerfile
- theia-full-docker/latest.package.json
- theia-full-docker/next.package.json
- theia-full-docker/settings.json
+ Fixes #410 
+ Adjust indentations in `theia-electron/package.json`
+ Remove `theia-full-docker/settings.json`
+ Specifying value directly in `theia-full-docker/latest.package.json` and `next.package.json`
> Clean up linting errors from eclint

- .travis.yml
- theia-cpp-electron/package.json
- theia-electron/package.json
The commit updates the `engines` field for both electron applications so it is aligned with upstream:
+ adjusts the engines field for the `theia-electron` app
+ adjusts the engines field for the `theia-cpp-electron` app
**How to Test:**
- build and package the `theia-electron` application
- the application should successfully start
> electron: adjust the engines field

- theia-cpp-docker/Dockerfile
- theia-go-docker/Dockerfile
- theia-rust-docker/Dockerfile
Finish splitting the last Dockerfiles to build Theia in its own image.
> split images: cpp, go and rust

- theia-full-docker/Dockerfile
Use multi-stage build for the `theia-full` image.
> full: split image

- .github/workflows/ci-cd.yml
- build_container.sh
- check_changed.sh
+ Partially address #444 
+ Replace Travis CI with GH Actions.
+ Only containing the build step, no test and deploy stage
> Migrate from Travis CI to GH Actions
